apiVersion: v1
kind: Service
metadata:
  name: nodejs-express-webpage-service
  labels:
    app: nodejs-express-webpage
spec:
  type: ClusterIP
  selector:
    app: nodejs-express-webpage
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP