apiVersion: v2
name: nodejs-express-webpage
description: A Helm chart for Node.js Express web application
type: application
version: 0.1.0
appVersion: 1.8.0
maintainers:
  - name: Your Name
    email: your.email@example.com