# Default values for nodejs-express-webpage
replicaCount: 1

image:
  repository: vtbwanderers63/nodejs-express-webpage
  tag: v1.8.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

config:
  name: "my-nodejs-app"
  environment: "development"