apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - patch: |-
      - op: add
        path: /metadata/labels/tier
        value: prod
      - op: replace
        path: /data/NAME
        value: PROD-Wanderer
      - op: replace
        path: /data/ENVIRONMENT
        value: prod
    target:
      kind: ConfigMap
      name: nodejs-express-config
  - patch: |-
      - op: add
        path: /metadata/labels/tier
        value: prod
    target:
      kind: Service
      name: nodejs-express-webpage-service
  - patch: |-
      - op: add
        path: /metadata/labels/tier
        value: prod
    target:
      kind: Deployment
      name: nodejs-express-webpage
