apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: add
        path: /metadata/labels/tier
        value: non-prod
      - op: replace
        path: /data/NAME
        value: DEV-Wanderer
      - op: replace
        path: /data/ENVIRONMENT
        value: dev
    target:
      kind: ConfigMap
      name: nodejs-express-config
  - patch: |-
      - op: add
        path: /metadata/labels/tier
        value: non-prod
    target:
      kind: Service
      name: nodejs-express-webpage-service
  - patch: |-
      - op: add
        path: /metadata/labels/tier
        value: non-prod
    target:
      kind: Deployment
      name: nodejs-express-webpage
